# Generated by Django 4.0.6 on 2022-07-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_compromisso', models.CharField(max_length=15)),
                ('nome_compromisso', models.CharField(max_length=200)),
                ('data_compromisso', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('local_compromisso', models.CharField(max_length=50)),
                ('observacoes', models.CharField(max_length=250)),
            ],
        ),
    ]
