# Generated by Django 4.0.6 on 2022-07-22 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'verbose_name': 'Tarefa'},
        ),
        migrations.AddField(
            model_name='tarefas',
            name='usuario',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='nome_compromisso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='observacoes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status_compromisso',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], max_length=200),
        ),
    ]
