# Generated by Django 4.0.6 on 2022-07-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'verbose_name': 'Tarefa'},
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='nome_compromisso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='observacoes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status_compromisso',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], max_length=200),
        ),
    ]
